apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-role-feature-busybox
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "delete", "patch", "create"]