kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-feature-busybox-admin
  namespace: feature-busybox
subjects:
- kind: ServiceAccount
  name: ns-reconciler-busybox
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io