kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-feature-busybox
  namespace: acm-busybox
subjects:
- kind: ServiceAccount
  name: ns-reconciler-busybox
  namespace: config-management-system
roleRef:
  kind: Role
  name: cluster-role-feature-busybox
  apiGroup: rbac.authorization.k8s.io