kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-role-feature-busybox
  namespace : devacm
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs:
  - "*"



# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: cluster-role-feature-busybox-pvc
# rules:
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs:
#   - "*"
# - apiGroups: [""]
#   resources: ["persistentvolumes,persistentvolumeclaims,persistentvolumeclaims/status"]
#   verbs:
#   - create
#   - delete
#   - get
#   - list
#   - watch
#   - update
# - apiGroups: [""]
#   resources: ["services"]
#   verbs:
#   - "*"
# - apiGroups: [""]
#   resources: ["deployments.apps"]
#   verbs:
#   - "*"