kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-role-feature-busybox
  namespace : devacm
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:
  - "*"
- apiGroups: [""]
  resources: ["services"]
  verbs:
  - "*"
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs:
  - "*"


kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-role-feature-busybox-pvc
  namespace : devacm
rules:
- apiGroups: [""]
  resources: ["persistentvolumes,persistentvolumeclaims,persistentvolumeclaims/status"]
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - update